##################################################
# file: SBMLEdit_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      bin/gencode
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from SBMLEdit_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
ReplaceGlobalParametersRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceGlobalParameters").pyclass

ReplaceGlobalParametersResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceGlobalParametersResponse").pyclass

ReplaceKineticLawParameterRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceKineticLawParameter").pyclass

ReplaceKineticLawParameterResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceKineticLawParameterResponse").pyclass

ValidateSBMLModelRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ValidateSBMLModel").pyclass

ValidateSBMLModelResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ValidateSBMLModelResponse").pyclass

ScaleKineticLawParameterRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleKineticLawParameter").pyclass

ScaleKineticLawParameterResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleKineticLawParameterResponse").pyclass

AddKineticLawParameterRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "AddKineticLawParameter").pyclass

AddKineticLawParameterResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "AddKineticLawParameterResponse").pyclass

AddBoundsToKineticLawRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "AddBoundsToKineticLaw").pyclass

AddBoundsToKineticLawResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "AddBoundsToKineticLawResponse").pyclass

ReplaceInitialConcentrationsOfSpeciesRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceInitialConcentrationsOfSpecies").pyclass

ReplaceInitialConcentrationsOfSpeciesResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceInitialConcentrationsOfSpeciesResponse").pyclass

GetVersionRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "GetVersion").pyclass

GetVersionResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "GetVersionResponse").pyclass

ValidateSBMLModelTextRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ValidateSBMLModelText").pyclass

ValidateSBMLModelTextResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ValidateSBMLModelTextResponse").pyclass

ValidateSBMLModelBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ValidateSBMLModelBase64Encoded").pyclass

ValidateSBMLModelBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ValidateSBMLModelBase64EncodedResponse").pyclass

ValidateSBMLModelGzippedBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ValidateSBMLModelGzippedBase64Encoded").pyclass

ValidateSBMLModelGzippedBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ValidateSBMLModelGzippedBase64EncodedResponse").pyclass

ReplaceGlobalParametersTextRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceGlobalParametersText").pyclass

ReplaceGlobalParametersTextResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceGlobalParametersTextResponse").pyclass

ReplaceGlobalParametersBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceGlobalParametersBase64Encoded").pyclass

ReplaceGlobalParametersBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceGlobalParametersBase64EncodedResponse").pyclass

ReplaceGlobalParametersGzippedBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceGlobalParametersGzippedBase64Encoded").pyclass

ReplaceGlobalParametersGzippedBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceGlobalParametersGzippedBase64EncodedResponse").pyclass

ReplaceKineticLawParameterTextRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceKineticLawParameterText").pyclass

ReplaceKineticLawParameterTextResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceKineticLawParameterTextResponse").pyclass

ReplaceKineticLawParameterBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceKineticLawParameterBase64Encoded").pyclass

ReplaceKineticLawParameterBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceKineticLawParameterBase64EncodedResponse").pyclass

ReplaceKineticLawParameterGzippedBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceKineticLawParameterGzippedBase64Encoded").pyclass

ReplaceKineticLawParameterGzippedBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceKineticLawParameterGzippedBase64EncodedResponse").pyclass

ScaleKineticLawParameterTextRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleKineticLawParameterText").pyclass

ScaleKineticLawParameterTextResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleKineticLawParameterTextResponse").pyclass

ScaleKineticLawParameterBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleKineticLawParameterBase64Encoded").pyclass

ScaleKineticLawParameterBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleKineticLawParameterBase64EncodedResponse").pyclass

ScaleKineticLawParameterGzippedBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleKineticLawParameterGzippedBase64Encoded").pyclass

ScaleKineticLawParameterGzippedBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleKineticLawParameterGzippedBase64EncodedResponse").pyclass

AddBoundsToKineticLawTextRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "AddBoundsToKineticLawText").pyclass

AddBoundsToKineticLawTextResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "AddBoundsToKineticLawTextResponse").pyclass

AddBoundsToKineticLawBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "AddBoundsToKineticLawBase64Encoded").pyclass

AddBoundsToKineticLawBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "AddBoundsToKineticLawBase64EncodedResponse").pyclass

AddBoundsToKineticLawGzippedBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "AddBoundsToKineticLawGzippedBase64Encoded").pyclass

AddBoundsToKineticLawGzippedBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "AddBoundsToKineticLawGzippedBase64EncodedResponse").pyclass

ReplaceInitialConcentrationsOfSpeciesTextRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceInitialConcentrationsOfSpeciesText").pyclass

ReplaceInitialConcentrationsOfSpeciesTextResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceInitialConcentrationsOfSpeciesTextResponse").pyclass

ReplaceInitialConcentrationsOfSpeciesBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceInitialConcentrationsOfSpeciesBase64Encoded").pyclass

ReplaceInitialConcentrationsOfSpeciesBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceInitialConcentrationsOfSpeciesBase64EncodedResponse").pyclass

ReplaceInitialConcentrationsOfSpeciesGzippedBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceInitialConcentrationsOfSpeciesGzippedBase64Encoded").pyclass

ReplaceInitialConcentrationsOfSpeciesGzippedBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ReplaceInitialConcentrationsOfSpeciesGzippedBase64EncodedResponse").pyclass

ScaleGlobalParametersTextRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleGlobalParametersText").pyclass

ScaleGlobalParametersTextResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleGlobalParametersTextResponse").pyclass

ScaleGlobalParametersBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleGlobalParametersBase64Encoded").pyclass

ScaleGlobalParametersBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleGlobalParametersBase64EncodedResponse").pyclass

ScaleGlobalParametersGzippedBase64EncodedRequest = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleGlobalParametersGzippedBase64Encoded").pyclass

ScaleGlobalParametersGzippedBase64EncodedResponse = GED("http://esysbio.org/service/bio/SBMLEdit", "ScaleGlobalParametersGzippedBase64EncodedResponse").pyclass


# Service Skeletons
class SBMLEdit(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/sbmledit', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_ReplaceGlobalParameters(self, ps, **kw):
        request = ps.Parse(ReplaceGlobalParametersRequest.typecode)
        return request,ReplaceGlobalParametersResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceGlobalParameters'] = 'soap_ReplaceGlobalParameters'
    root[(ReplaceGlobalParametersRequest.typecode.nspname,ReplaceGlobalParametersRequest.typecode.pname)] = 'soap_ReplaceGlobalParameters'

    def soap_ReplaceKineticLawParameter(self, ps, **kw):
        request = ps.Parse(ReplaceKineticLawParameterRequest.typecode)
        return request,ReplaceKineticLawParameterResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceKineticLawParameter'] = 'soap_ReplaceKineticLawParameter'
    root[(ReplaceKineticLawParameterRequest.typecode.nspname,ReplaceKineticLawParameterRequest.typecode.pname)] = 'soap_ReplaceKineticLawParameter'

    def soap_ValidateSBMLModel(self, ps, **kw):
        request = ps.Parse(ValidateSBMLModelRequest.typecode)
        return request,ValidateSBMLModelResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ValidateSBMLModel'] = 'soap_ValidateSBMLModel'
    root[(ValidateSBMLModelRequest.typecode.nspname,ValidateSBMLModelRequest.typecode.pname)] = 'soap_ValidateSBMLModel'

    def soap_ScaleKineticLawParameter(self, ps, **kw):
        request = ps.Parse(ScaleKineticLawParameterRequest.typecode)
        return request,ScaleKineticLawParameterResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ScaleKineticLawParameter'] = 'soap_ScaleKineticLawParameter'
    root[(ScaleKineticLawParameterRequest.typecode.nspname,ScaleKineticLawParameterRequest.typecode.pname)] = 'soap_ScaleKineticLawParameter'

    def soap_AddKineticLawParameter(self, ps, **kw):
        request = ps.Parse(AddKineticLawParameterRequest.typecode)
        return request,AddKineticLawParameterResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/AddKineticLawParameter'] = 'soap_AddKineticLawParameter'
    root[(AddKineticLawParameterRequest.typecode.nspname,AddKineticLawParameterRequest.typecode.pname)] = 'soap_AddKineticLawParameter'

    def soap_AddBoundsToKineticLaw(self, ps, **kw):
        request = ps.Parse(AddBoundsToKineticLawRequest.typecode)
        return request,AddBoundsToKineticLawResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/AddBoundsToKineticLaw'] = 'soap_AddBoundsToKineticLaw'
    root[(AddBoundsToKineticLawRequest.typecode.nspname,AddBoundsToKineticLawRequest.typecode.pname)] = 'soap_AddBoundsToKineticLaw'

    def soap_ReplaceInitialConcentrationsOfSpecies(self, ps, **kw):
        request = ps.Parse(ReplaceInitialConcentrationsOfSpeciesRequest.typecode)
        return request,ReplaceInitialConcentrationsOfSpeciesResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceInitialConcentrationsOfSpecies'] = 'soap_ReplaceInitialConcentrationsOfSpecies'
    root[(ReplaceInitialConcentrationsOfSpeciesRequest.typecode.nspname,ReplaceInitialConcentrationsOfSpeciesRequest.typecode.pname)] = 'soap_ReplaceInitialConcentrationsOfSpecies'

    def soap_GetVersion(self, ps, **kw):
        request = ps.Parse(GetVersionRequest.typecode)
        return request,GetVersionResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/GetVersion'] = 'soap_GetVersion'
    root[(GetVersionRequest.typecode.nspname,GetVersionRequest.typecode.pname)] = 'soap_GetVersion'

    def soap_ValidateSBMLModelText(self, ps, **kw):
        request = ps.Parse(ValidateSBMLModelTextRequest.typecode)
        return request,ValidateSBMLModelTextResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ValidateSBMLModelText'] = 'soap_ValidateSBMLModelText'
    root[(ValidateSBMLModelTextRequest.typecode.nspname,ValidateSBMLModelTextRequest.typecode.pname)] = 'soap_ValidateSBMLModelText'

    def soap_ValidateSBMLModelBase64Encoded(self, ps, **kw):
        request = ps.Parse(ValidateSBMLModelBase64EncodedRequest.typecode)
        return request,ValidateSBMLModelBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ValidateSBMLModelBase64Encoded'] = 'soap_ValidateSBMLModelBase64Encoded'
    root[(ValidateSBMLModelBase64EncodedRequest.typecode.nspname,ValidateSBMLModelBase64EncodedRequest.typecode.pname)] = 'soap_ValidateSBMLModelBase64Encoded'

    def soap_ValidateSBMLModelGzippedBase64Encoded(self, ps, **kw):
        request = ps.Parse(ValidateSBMLModelGzippedBase64EncodedRequest.typecode)
        return request,ValidateSBMLModelGzippedBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ValidateSBMLModelGzippedBase64Encoded'] = 'soap_ValidateSBMLModelGzippedBase64Encoded'
    root[(ValidateSBMLModelGzippedBase64EncodedRequest.typecode.nspname,ValidateSBMLModelGzippedBase64EncodedRequest.typecode.pname)] = 'soap_ValidateSBMLModelGzippedBase64Encoded'

    def soap_ReplaceGlobalParametersText(self, ps, **kw):
        request = ps.Parse(ReplaceGlobalParametersTextRequest.typecode)
        return request,ReplaceGlobalParametersTextResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceGlobalParametersText'] = 'soap_ReplaceGlobalParametersText'
    root[(ReplaceGlobalParametersTextRequest.typecode.nspname,ReplaceGlobalParametersTextRequest.typecode.pname)] = 'soap_ReplaceGlobalParametersText'

    def soap_ReplaceGlobalParametersBase64Encoded(self, ps, **kw):
        request = ps.Parse(ReplaceGlobalParametersBase64EncodedRequest.typecode)
        return request,ReplaceGlobalParametersBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceGlobalParametersBase64Encoded'] = 'soap_ReplaceGlobalParametersBase64Encoded'
    root[(ReplaceGlobalParametersBase64EncodedRequest.typecode.nspname,ReplaceGlobalParametersBase64EncodedRequest.typecode.pname)] = 'soap_ReplaceGlobalParametersBase64Encoded'

    def soap_ReplaceGlobalParametersGzippedBase64Encoded(self, ps, **kw):
        request = ps.Parse(ReplaceGlobalParametersGzippedBase64EncodedRequest.typecode)
        return request,ReplaceGlobalParametersGzippedBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceGlobalParametersGzippedBase64Encoded'] = 'soap_ReplaceGlobalParametersGzippedBase64Encoded'
    root[(ReplaceGlobalParametersGzippedBase64EncodedRequest.typecode.nspname,ReplaceGlobalParametersGzippedBase64EncodedRequest.typecode.pname)] = 'soap_ReplaceGlobalParametersGzippedBase64Encoded'

    def soap_ReplaceKineticLawParameterText(self, ps, **kw):
        request = ps.Parse(ReplaceKineticLawParameterTextRequest.typecode)
        return request,ReplaceKineticLawParameterTextResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceKineticLawParameterText'] = 'soap_ReplaceKineticLawParameterText'
    root[(ReplaceKineticLawParameterTextRequest.typecode.nspname,ReplaceKineticLawParameterTextRequest.typecode.pname)] = 'soap_ReplaceKineticLawParameterText'

    def soap_ReplaceKineticLawParameterBase64Encoded(self, ps, **kw):
        request = ps.Parse(ReplaceKineticLawParameterBase64EncodedRequest.typecode)
        return request,ReplaceKineticLawParameterBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceKineticLawParameterBase64Encoded'] = 'soap_ReplaceKineticLawParameterBase64Encoded'
    root[(ReplaceKineticLawParameterBase64EncodedRequest.typecode.nspname,ReplaceKineticLawParameterBase64EncodedRequest.typecode.pname)] = 'soap_ReplaceKineticLawParameterBase64Encoded'

    def soap_ReplaceKineticLawParameterGzippedBase64Encoded(self, ps, **kw):
        request = ps.Parse(ReplaceKineticLawParameterGzippedBase64EncodedRequest.typecode)
        return request,ReplaceKineticLawParameterGzippedBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceKineticLawParameterGzippedBase64Encoded'] = 'soap_ReplaceKineticLawParameterGzippedBase64Encoded'
    root[(ReplaceKineticLawParameterGzippedBase64EncodedRequest.typecode.nspname,ReplaceKineticLawParameterGzippedBase64EncodedRequest.typecode.pname)] = 'soap_ReplaceKineticLawParameterGzippedBase64Encoded'

    def soap_ScaleKineticLawParameterText(self, ps, **kw):
        request = ps.Parse(ScaleKineticLawParameterTextRequest.typecode)
        return request,ScaleKineticLawParameterTextResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ScaleKineticLawParameterText'] = 'soap_ScaleKineticLawParameterText'
    root[(ScaleKineticLawParameterTextRequest.typecode.nspname,ScaleKineticLawParameterTextRequest.typecode.pname)] = 'soap_ScaleKineticLawParameterText'

    def soap_ScaleKineticLawParameterBase64Encoded(self, ps, **kw):
        request = ps.Parse(ScaleKineticLawParameterBase64EncodedRequest.typecode)
        return request,ScaleKineticLawParameterBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ScaleKineticLawParameterBase64Encoded'] = 'soap_ScaleKineticLawParameterBase64Encoded'
    root[(ScaleKineticLawParameterBase64EncodedRequest.typecode.nspname,ScaleKineticLawParameterBase64EncodedRequest.typecode.pname)] = 'soap_ScaleKineticLawParameterBase64Encoded'

    def soap_ScaleKineticLawParameterGzippedBase64Encoded(self, ps, **kw):
        request = ps.Parse(ScaleKineticLawParameterGzippedBase64EncodedRequest.typecode)
        return request,ScaleKineticLawParameterGzippedBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ScaleKineticLawParameterGzippedBase64Encoded'] = 'soap_ScaleKineticLawParameterGzippedBase64Encoded'
    root[(ScaleKineticLawParameterGzippedBase64EncodedRequest.typecode.nspname,ScaleKineticLawParameterGzippedBase64EncodedRequest.typecode.pname)] = 'soap_ScaleKineticLawParameterGzippedBase64Encoded'

    def soap_AddBoundsToKineticLawText(self, ps, **kw):
        request = ps.Parse(AddBoundsToKineticLawTextRequest.typecode)
        return request,AddBoundsToKineticLawTextResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/AddBoundsToKineticLawText'] = 'soap_AddBoundsToKineticLawText'
    root[(AddBoundsToKineticLawTextRequest.typecode.nspname,AddBoundsToKineticLawTextRequest.typecode.pname)] = 'soap_AddBoundsToKineticLawText'

    def soap_AddBoundsToKineticLawBase64Encoded(self, ps, **kw):
        request = ps.Parse(AddBoundsToKineticLawBase64EncodedRequest.typecode)
        return request,AddBoundsToKineticLawBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/AddBoundsToKineticLawBase64Encoded'] = 'soap_AddBoundsToKineticLawBase64Encoded'
    root[(AddBoundsToKineticLawBase64EncodedRequest.typecode.nspname,AddBoundsToKineticLawBase64EncodedRequest.typecode.pname)] = 'soap_AddBoundsToKineticLawBase64Encoded'

    def soap_AddBoundsToKineticLawGzippedBase64Encoded(self, ps, **kw):
        request = ps.Parse(AddBoundsToKineticLawGzippedBase64EncodedRequest.typecode)
        return request,AddBoundsToKineticLawGzippedBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/AddBoundsToKineticLawGzippedBase64Encoded'] = 'soap_AddBoundsToKineticLawGzippedBase64Encoded'
    root[(AddBoundsToKineticLawGzippedBase64EncodedRequest.typecode.nspname,AddBoundsToKineticLawGzippedBase64EncodedRequest.typecode.pname)] = 'soap_AddBoundsToKineticLawGzippedBase64Encoded'

    def soap_ReplaceInitialConcentrationsOfSpeciesText(self, ps, **kw):
        request = ps.Parse(ReplaceInitialConcentrationsOfSpeciesTextRequest.typecode)
        return request,ReplaceInitialConcentrationsOfSpeciesTextResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceInitialConcentrationsOfSpeciesText'] = 'soap_ReplaceInitialConcentrationsOfSpeciesText'
    root[(ReplaceInitialConcentrationsOfSpeciesTextRequest.typecode.nspname,ReplaceInitialConcentrationsOfSpeciesTextRequest.typecode.pname)] = 'soap_ReplaceInitialConcentrationsOfSpeciesText'

    def soap_ReplaceInitialConcentrationsOfSpeciesBase64Encoded(self, ps, **kw):
        request = ps.Parse(ReplaceInitialConcentrationsOfSpeciesBase64EncodedRequest.typecode)
        return request,ReplaceInitialConcentrationsOfSpeciesBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceInitialConcentrationsOfSpeciesBase64Encoded'] = 'soap_ReplaceInitialConcentrationsOfSpeciesBase64Encoded'
    root[(ReplaceInitialConcentrationsOfSpeciesBase64EncodedRequest.typecode.nspname,ReplaceInitialConcentrationsOfSpeciesBase64EncodedRequest.typecode.pname)] = 'soap_ReplaceInitialConcentrationsOfSpeciesBase64Encoded'

    def soap_ReplaceInitialConcentrationsOfSpeciesGzippedBase64Encoded(self, ps, **kw):
        request = ps.Parse(ReplaceInitialConcentrationsOfSpeciesGzippedBase64EncodedRequest.typecode)
        return request,ReplaceInitialConcentrationsOfSpeciesGzippedBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ReplaceInitialConcentrationsOfSpeciesGzippedBase64Encoded'] = 'soap_ReplaceInitialConcentrationsOfSpeciesGzippedBase64Encoded'
    root[(ReplaceInitialConcentrationsOfSpeciesGzippedBase64EncodedRequest.typecode.nspname,ReplaceInitialConcentrationsOfSpeciesGzippedBase64EncodedRequest.typecode.pname)] = 'soap_ReplaceInitialConcentrationsOfSpeciesGzippedBase64Encoded'

    def soap_ScaleGlobalParametersText(self, ps, **kw):
        request = ps.Parse(ScaleGlobalParametersTextRequest.typecode)
        return request,ScaleGlobalParametersTextResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ScaleGlobalParametersText'] = 'soap_ScaleGlobalParametersText'
    root[(ScaleGlobalParametersTextRequest.typecode.nspname,ScaleGlobalParametersTextRequest.typecode.pname)] = 'soap_ScaleGlobalParametersText'

    def soap_ScaleGlobalParametersBase64Encoded(self, ps, **kw):
        request = ps.Parse(ScaleGlobalParametersBase64EncodedRequest.typecode)
        return request,ScaleGlobalParametersBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ScaleGlobalParametersBase64Encoded'] = 'soap_ScaleGlobalParametersBase64Encoded'
    root[(ScaleGlobalParametersBase64EncodedRequest.typecode.nspname,ScaleGlobalParametersBase64EncodedRequest.typecode.pname)] = 'soap_ScaleGlobalParametersBase64Encoded'

    def soap_ScaleGlobalParametersGzippedBase64Encoded(self, ps, **kw):
        request = ps.Parse(ScaleGlobalParametersGzippedBase64EncodedRequest.typecode)
        return request,ScaleGlobalParametersGzippedBase64EncodedResponse()

    soapAction['http://esysbio.org/service/bio/SBMLEdit/ScaleGlobalParametersGzippedBase64Encoded'] = 'soap_ScaleGlobalParametersGzippedBase64Encoded'
    root[(ScaleGlobalParametersGzippedBase64EncodedRequest.typecode.nspname,ScaleGlobalParametersGzippedBase64EncodedRequest.typecode.pname)] = 'soap_ScaleGlobalParametersGzippedBase64Encoded'

